function buf = rtuwritereg(devaddr, regH, regL, numreg, numbytes, value)
buf = [ ...
    devaddr, ...
    16, ...
    regH, regL, ...
    flip(typecast(uint16(numreg), 'uint8')), ...
    numbytes, ...
    flip(typecast(value, 'uint8')) ...
    ];
buf = append_crc(buf);
end

